// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "product/product.proto" (package "product", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ProductService } from "./product";
import type { ListProductAdminResponse } from "./product";
import type { ListProductAdminRequest } from "./product";
import type { DeleteProductResponse } from "./product";
import type { DeleteProductRequest } from "./product";
import type { EditProductResponse } from "./product";
import type { EditProductRequest } from "./product";
import type { DetailProductResponse } from "./product";
import type { DetailProductRequest } from "./product";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreateProductResponse } from "./product";
import type { CreateProductRequest } from "./product";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service product.ProductService
 */
export interface IProductServiceClient {
    /**
     * @generated from protobuf rpc: CreateProduct
     */
    createProduct(input: CreateProductRequest, options?: RpcOptions): UnaryCall<CreateProductRequest, CreateProductResponse>;
    /**
     * @generated from protobuf rpc: DetailProduct
     */
    detailProduct(input: DetailProductRequest, options?: RpcOptions): UnaryCall<DetailProductRequest, DetailProductResponse>;
    /**
     * @generated from protobuf rpc: EditProduct
     */
    editProduct(input: EditProductRequest, options?: RpcOptions): UnaryCall<EditProductRequest, EditProductResponse>;
    /**
     * @generated from protobuf rpc: DeleteProduct
     */
    deleteProduct(input: DeleteProductRequest, options?: RpcOptions): UnaryCall<DeleteProductRequest, DeleteProductResponse>;
    /**
     * @generated from protobuf rpc: ListProductAdmin
     */
    listProductAdmin(input: ListProductAdminRequest, options?: RpcOptions): UnaryCall<ListProductAdminRequest, ListProductAdminResponse>;
}
/**
 * @generated from protobuf service product.ProductService
 */
export class ProductServiceClient implements IProductServiceClient, ServiceInfo {
    typeName = ProductService.typeName;
    methods = ProductService.methods;
    options = ProductService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateProduct
     */
    createProduct(input: CreateProductRequest, options?: RpcOptions): UnaryCall<CreateProductRequest, CreateProductResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateProductRequest, CreateProductResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DetailProduct
     */
    detailProduct(input: DetailProductRequest, options?: RpcOptions): UnaryCall<DetailProductRequest, DetailProductResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<DetailProductRequest, DetailProductResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: EditProduct
     */
    editProduct(input: EditProductRequest, options?: RpcOptions): UnaryCall<EditProductRequest, EditProductResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<EditProductRequest, EditProductResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteProduct
     */
    deleteProduct(input: DeleteProductRequest, options?: RpcOptions): UnaryCall<DeleteProductRequest, DeleteProductResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteProductRequest, DeleteProductResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListProductAdmin
     */
    listProductAdmin(input: ListProductAdminRequest, options?: RpcOptions): UnaryCall<ListProductAdminRequest, ListProductAdminResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListProductAdminRequest, ListProductAdminResponse>("unary", this._transport, method, opt, input);
    }
}
